/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.notificare;

import java.util.HashMap;
import java.util.List;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import re.notifica.Notificare;
import re.notifica.NotificareCallback;
import re.notifica.NotificareError;
import re.notifica.beacon.BeaconRangingListener;
import re.notifica.billing.BillingManager;
import re.notifica.billing.BillingResult;
import re.notifica.billing.Purchase;
import re.notifica.model.NotificareBeacon;
import re.notifica.model.NotificareProduct;
import re.notifica.model.NotificareRegion;
import re.notifica.model.NotificareUser;
import re.notifica.ui.UserPreferencesActivity;
import ti.notificare.IntentReceiver;


@Kroll.module(name="NotificareTitaniumAndroid", id="ti.notificare")
public class NotificareTitaniumAndroidModule extends KrollModule implements BeaconRangingListener,Notificare.OnBillingReadyListener, BillingManager.OnRefreshFinishedListener, BillingManager.OnPurchaseFinishedListener
{

	// Standard Debugging variables
	private static final String LCAT = "NotificareTitaniumAndroidModule";
	private static final boolean DBG = TiConfig.LOGD;
	
	public String userID;
	public String userName;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public NotificareTitaniumAndroidModule()
	{
		super(LCAT);
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		Notificare.shared().launch(app);
		Notificare.shared().setIntentReceiver(IntentReceiver.class);
	
	}

	// Methods
	@Kroll.method
	public void enableNotifications()
	{
		Notificare.shared().enableNotifications();
	}

	@Kroll.method
	public void enableLocationUpdates()
	{
		Notificare.shared().enableLocationUpdates();
	}
	
	@Kroll.method
	public void enableBeacons()
	{
		Notificare.shared().enableBeacons();
	}
	
	@Kroll.method
	public void enableBilling()
	{
		Notificare.shared().enableBilling();
	}
	
	@Kroll.method
	public void registerDevice(String deviceId){
		
		Notificare.shared().registerDevice(deviceId, this.userID, this.userName, new NotificareCallback<String>() {

			@Override
			public void onSuccess(String result) {
				
				TiApplication appContext = TiApplication.getInstance();
				HashMap<String, Object> event = new HashMap<String, Object>();
			    event.put("device", result);
		    	appContext.getModuleByName("NotificareTitaniumAndroidModule").fireEvent("registered", event);
		    	
				Notificare.shared().fetchDeviceTags(new NotificareCallback<List<String>>() {

					@Override
					public void onError(NotificareError arg0) {
						// TODO Auto-generated method stub

					}

					@Override
					public void onSuccess(List<String> arg0) {

						TiApplication appContext = TiApplication.getInstance();
						HashMap<String, Object> event = new HashMap<String, Object>();
					    event.put("tags", arg0);
				    	appContext.getModuleByName("NotificareTitaniumAndroidModule").fireEvent("tags", event);
						 
					}
					
				});
			}

			@Override
			public void onError(NotificareError error) {
				Log.e(LCAT, "Error registering device", error);
			}
        	
        });
		
	}
	
	@Kroll.method
	public void addTags(List<String> tags)
	{
		Notificare.shared().addDeviceTags(tags, new NotificareCallback<Boolean>(){

			@Override
			public void onError(NotificareError arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void onSuccess(Boolean arg0) {
				
				Notificare.shared().fetchDeviceTags(new NotificareCallback<List<String>>() {

					@Override
					public void onError(NotificareError arg0) {
						// TODO Auto-generated method stub

					}

					@Override
					public void onSuccess(List<String> arg0) {

						TiApplication appContext = TiApplication.getInstance();
						HashMap<String, Object> event = new HashMap<String, Object>();
					    event.put("tags", arg0);
				    	appContext.getModuleByName("NotificareTitaniumAndroidModule").fireEvent("tags", event);
						 
					}
					
				});
				
			}

		});
	}
	
	@Kroll.method
	public void removeTag(String tag)
	{
		Notificare.shared().removeDeviceTag(tag, new NotificareCallback<Boolean>(){

			@Override
			public void onError(NotificareError arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void onSuccess(Boolean arg0) {
				
				Notificare.shared().fetchDeviceTags(new NotificareCallback<List<String>>() {

					@Override
					public void onError(NotificareError arg0) {
						// TODO Auto-generated method stub

					}

					@Override
					public void onSuccess(List<String> arg0) {

						TiApplication appContext = TiApplication.getInstance();
						HashMap<String, Object> event = new HashMap<String, Object>();
					    event.put("tags", arg0);
				    	appContext.getModuleByName("NotificareTitaniumAndroidModule").fireEvent("tags", event);
						 
					}
					
				});
				
			}
			
		});
	}
	
	
	@Kroll.method
	public void clearTags()
	{
		Notificare.shared().clearDeviceTags(new NotificareCallback<Boolean>(){

			@Override
			public void onError(NotificareError arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void onSuccess(Boolean arg0) {
				
				Notificare.shared().fetchDeviceTags(new NotificareCallback<List<String>>() {

					@Override
					public void onError(NotificareError arg0) {
						// TODO Auto-generated method stub

					}

					@Override
					public void onSuccess(List<String> arg0) {

						TiApplication appContext = TiApplication.getInstance();
						HashMap<String, Object> event = new HashMap<String, Object>();
					    event.put("tags", arg0);
				    	appContext.getModuleByName("NotificareTitaniumAndroidModule").fireEvent("tags", event);
						 
					}
					
				});
				
			}
			
		});
	}
	
	// Properties
	@Kroll.getProperty
	public String userID()
	{
		return this.userID;
	}
	
	public String userName()
	{
		return this.userName;
	}


	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(LCAT, "set example property: " + value);
	}
	
	public void getTags(){
		Notificare.shared().fetchDeviceTags(new NotificareCallback<List<String>>() {

			@Override
			public void onError(NotificareError arg0) {
				// TODO Auto-generated method stub

			}

			@Override
			public void onSuccess(List<String> arg0) {

				TiApplication appContext = TiApplication.getInstance();
				HashMap<String, Object> event = new HashMap<String, Object>();
			    event.put("tags", arg0);
		    	appContext.getModuleByName("NotificareTitaniumAndroidModule").fireEvent("tags", event);
				 
			}
			
		});
	}

	@Override
	public void onPurchaseFinished(BillingResult arg0, Purchase arg1) {
		
		TiApplication appContext = TiApplication.getInstance();
		HashMap<String, Object> event = new HashMap<String, Object>();
	    event.put("transaction", arg1);
    	appContext.getModuleByName("NotificareTitaniumAndroidModule").fireEvent("transaction", event);
		
	}

	@Override
	public void onRefreshFailed(NotificareError arg0) {
		// TODO Auto-generated method stub
		TiApplication appContext = TiApplication.getInstance();
		HashMap<String, Object> event = new HashMap<String, Object>();
	    event.put("error", arg0);
    	appContext.getModuleByName("NotificareTitaniumAndroidModule").fireEvent("errors", event);
	}

	@Override
	public void onRefreshFinished() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onBillingReady() {
		TiApplication appContext = TiApplication.getInstance();
    	appContext.getModuleByName("NotificareTitaniumAndroidModule").fireEvent("store", new KrollDict());
	}

	@Override
	public void onRangingBeacons(List<NotificareBeacon> arg0) {
		TiApplication appContext = TiApplication.getInstance();
		HashMap<String, Object> event = new HashMap<String, Object>();
	    event.put("beacons", arg0);
		appContext.getModuleByName("NotificareTitaniumAndroidModule").fireEvent("range", event);
		
	}

}

